#!/bin/bash

set -e

cd "$(dirname "$0")"

# Default skipped tasks (can be overridden by env var)
: "${SKIP_TASKS:=test validate integration-test}"
IFS=' ' read -ra skip_tasks <<<"$SKIP_TASKS"

tasks=("build" "validate" "sync-grpc-py" "test" "integration-test" "package")

for task in "${tasks[@]}"; do
  for skip_task in "${skip_tasks[@]}"; do
    if [ "$task" = "$skip_task" ]; then
      continue 2
    fi
  done

  ./"$task"
done
